Traceback (most recent call last):
  File "/home/tbsexton/.pyenv/versions/3.10.9/envs/text-data/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/tbsexton/.pyenv/versions/3.10.9/envs/text-data/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/tbsexton/.pyenv/versions/3.10.9/envs/text-data/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/tbsexton/.pyenv/versions/3.10.9/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/tbsexton/.pyenv/versions/3.10.9/envs/text-data/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/tbsexton/.pyenv/versions/3.10.9/envs/text-data/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/tbsexton/.pyenv/versions/3.10.9/envs/text-data/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import spacy
import numpy as np
from scipy.spatial import distance
# from gensim.models import Word2Vec
import nltk
import pandas as pd
import flair
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 7[0m
[1;32m      5[0m [38;5;28;01mimport[39;00m [38;5;21;01mnltk[39;00m
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m----> 7[0m [38;5;28;01mimport[39;00m [38;5;21;01mflair[39;00m

[0;31mModuleNotFoundError[0m: No module named 'flair'

